package frc.robot;

public enum RobotState {
    IDLE,
    HOME,
    INTAKING,
    PREPARING_SHOOTER_AND_INTAKING,
    PREPARING_SHOOTER,
    SHOOTING_RECOVERY,
    SHOOTING,
    SHOOTING_AND_INTAKING,
    UNJAM
}
